name: Do Something
on:
  workflow_dispatch:
  release:
    types:
      - published

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  issues: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/manual-approval
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: do something
        run: echo "Hello"
