name: Manual Approval
description: 手動の承認を行うアクション

inputs:
  approvers:
    description: Comma-delimited list of all required approvers.
    required: false
    default: MasahiroKanatani,teknocat,amotz,briete,yuji-shimoda
  minimum-approvals:
    description: Minimum number of approvals required
    default: 1
    required: false
  token: 
    required: true

runs:
  using: composite
  steps:
    - uses: actions/github-script@v7
      id: set_issue_title_body
      name: "Set Issue Title & Body"
      with:
        script: |
          let issueTitle = "";
          let issueBody = "";

          switch("${{ github.event_name }}") {
            case "release":
              issueTitle = ":rocket: Release ${{ github.event.release.name }}";
              issueBody = `${{ github.event.release.body }}
          - ${{ github.event.release.html_url }}`;
              break;
            case "workflow_dispatch":
              issueTitle = ":ambulance: Manual Deploy ${{ github.ref_name }}";
              issueBody = `## 確認事項
          - [ ] :warning: 本番環境に対して手動でのデプロイを実施します。
          - [ ] デプロイ対象のタグ: **${{ github.ref_name }}**`;
              break;
            default:
              throw new Error(`Unexpected event: ${{ github.event_name }}`);
          }

          core.setOutput('ISSUE_TITLE', issueTitle);
          core.setOutput('ISSUE_BODY', issueBody);
    - uses: trstringer/manual-approval@v1
      with:
        secret: ${{ inputs.token }}
        approvers: ${{ inputs.approvers }}
        minimum-approvals: ${{ inputs.minimum-approvals }}
        issue-title: ${{ steps.set_issue_title_body.outputs.ISSUE_TITLE }}
        issue-body: ${{ steps.set_issue_title_body.outputs.ISSUE_BODY }}
